#include <stddef.h>

size_t oracle_size_u8_2(void);
size_t oracle_size_u16_2(void);
size_t oracle_holder_size(void);
size_t oracle_layout_box_size(void);
size_t oracle_layout_box_align(void);
size_t oracle_payload_offset(void);
size_t oracle_nested_size(void);
size_t oracle_envelope_size(void);
size_t oracle_envelope_box_offset(void);
size_t oracle_envelope_tail_offset(void);
size_t oracle_body_box_size_u8(void);
size_t oracle_body_box_size_u64(void);
size_t oracle_body_box_align_u8(void);
size_t oracle_body_box_align_u64(void);
size_t oracle_body_box_value_offset_u8(void);
size_t oracle_body_box_value_offset_u64(void);
size_t oracle_body_box_array_size_u8(void);
size_t oracle_body_box_array_size_u64(void);
size_t oracle_body_nested_box_size_u8(void);
size_t oracle_body_nested_box_size_u64(void);
size_t oracle_body_layout_box_size_u8_2(void);
size_t oracle_body_layout_box_size_u64_2(void);
size_t oracle_body_layout_box_payload_offset_u8_2(void);
size_t oracle_body_layout_box_payload_offset_u64_2(void);
