#include <stdlib.h>
struct FasTagRecord { int first; unsigned char second; };
typedef struct { unsigned char byte; int word; } FasAnonymousRecord;
struct FasAliasRecord { int value; };
typedef struct FasAliasRecord FasAlias;
struct FasInnerRecord { short left; int right; };
struct FasNestedRecord { struct FasInnerRecord inner; int values[2]; };
struct FasSelfRecord { struct FasSelfRecord *next; int value; };
struct __attribute__((aligned(16))) FasAlignedRecord { int value; };
struct __attribute__((packed)) FasPackedRecord { unsigned char byte; int word; };
union FasUnionRecord { int value; unsigned char byte; };
void fas_union_pointer(union FasUnionRecord *value);
union FasUnionRecord *fas_union_pointer_result(void);
struct FasBitfieldRecord { unsigned int value : 3; };
struct FasFlexibleRecord { int length; unsigned char data[]; };
struct FasAnonymousMemberRecord { union { int integer; unsigned char byte; }; };
struct FasFloatRecord { float value; };
typedef int (*FasCallback)(int);
struct FasFunctionPointerRecord { int (*callback)(int); };
extern FasCallback fas_callback_global;
FasCallback fas_callback_result(void);
int fas_callback_parameter(FasCallback callback);
struct FasFieldNamesRecord { int handle; int len; int view; int i32; };
struct FasKeywordFieldRecord { int opaque; int fn; int var; };
struct FasConstFieldRecord { const int value; };
struct FasNestedConstFieldRecord { struct FasConstFieldRecord inner; };
struct FasConstPointerRecord { const char *value; };
extern struct FasSelfRecord fas_address_self;
extern struct FasNestedRecord fas_address_nested;
extern struct FasSelfRecord fas_address_self_array[2];
